// Core widget context-action providers. These contribute the section-1
// (Context band) rows that are specific to a widget. The universal sections
// (AI Assist, Create, Convert, Organise, Share, Advanced, Destructive) are
// added by the resolver for every widget, so a provider only declares what is
// genuinely specific to its kind. Importing this module once registers them.

import { MenuSection, type MenuContribution } from './types'
import { registerWidgetContextActions } from './registry'
import { useWidgetStore } from '../../stores/widgets'
import { useWidgetSetup } from '../../stores/widgetSetup'
import { useTablesStore } from '../../stores/tables'
import { createConnectedTool } from '../createConnectedTool'
import { hasChecklist, toggleChecklist } from '../stickyText'

// "Build with AI" drafts a list of items to add in the widget's own format and
// lets the user approve them (the tables-style AI setup, generalised). Offered
// on the widget kinds the main-process generator supports (sticky, note,
// markdown, card).
function buildWithAiRow(widgetId: string): MenuContribution {
  return {
    id: 'core/build-with-ai',
    section: MenuSection.Context,
    priority: -1, // sits at the very top of the context band
    label: 'Build with AI',
    icon: 'auto_awesome',
    onSelect: () => useWidgetSetup.getState().start(widgetId)
  }
}

// Sticky: a real widget-specific action that proves the registration path end
// to end. Toggling the checklist is a pure transform on the sticky's text, so
// it is safe to drive from the menu.
registerWidgetContextActions('sticky', (ctx) => {
  if (ctx.object.type !== 'widget') return { context: [] }
  const w = ctx.object.widget
  const checklist = hasChecklist(w.content || '')
  return {
    context: [
      buildWithAiRow(w.id),
      {
        id: 'sticky/checklist',
        section: MenuSection.Context,
        priority: 0,
        label: checklist ? 'Remove checkboxes' : 'Make a checklist',
        icon: 'checklist',
        onSelect: () => void useWidgetStore.getState().update(w.id, { content: toggleChecklist(w.content || '') })
      }
    ]
  }
})

// The remaining widgets the generator supports get Build with AI as their
// context action. Mindmap drafts branches; diagram drafts nodes.
for (const kind of ['note', 'markdown', 'card', 'mindmap', 'diagram'] as const) {
  registerWidgetContextActions(kind, (ctx) => {
    if (ctx.object.type !== 'widget') return { context: [] }
    return { context: [buildWithAiRow(ctx.object.widget.id)] }
  })
}

// Living Doc: the document is regenerated by AI, so manual AI Assist rewrites of
// the body would be overwritten on the next cycle. Suppress AI Assist there and
// offer a regenerate-now action in the Context band instead.
registerWidgetContextActions('living-doc', (ctx) => {
  if (ctx.object.type !== 'widget') return { context: [] }
  const w = ctx.object.widget
  return {
    context: [
      {
        id: 'living-doc/regenerate',
        section: MenuSection.Context,
        priority: 0,
        label: 'Regenerate now',
        icon: 'autorenew',
        onSelect: () => void window.api.livingPage.regenerate(w.id)
      }
    ],
    suppress: { 'ai-assist': true }
  }
})

// Table: "Add row" applies anywhere on the table (header or a cell), so it is a
// wildcard. The cell provider below adds the row-specific actions that need to
// know WHICH row was clicked.
registerWidgetContextActions('table', (ctx) => {
  if (ctx.object.type !== 'widget') return { context: [] }
  const tableId = ctx.object.widget.content
  return {
    context: [
      {
        id: 'table/add-row',
        section: MenuSection.Context,
        priority: 0,
        label: 'Add row',
        icon: 'add',
        onSelect: () => void useTablesStore.getState().addRow(tableId)
      }
    ]
  }
})

// Table cell: row-specific actions on the cell that was right-clicked, plus the
// universal sections seeded from the cell text (Create a sticky from this cell,
// AI Assist on the cell, ...). Operates through the tables store directly.
registerWidgetContextActions('table', 'cell', (ctx) => {
  if (ctx.object.type !== 'widget') return { context: [] }
  const tableId = (ctx.sub?.payload?.tableId as string) || ctx.object.widget.content
  const rowId = ctx.sub?.payload?.rowId as string | undefined
  if (!rowId) return { context: [] }
  return {
    context: [
      {
        id: 'table/duplicate-row',
        section: MenuSection.Context,
        priority: 1,
        label: 'Duplicate row',
        icon: 'content_copy',
        onSelect: () => {
          const store = useTablesStore.getState()
          const tableRows = store.rows[tableId] ?? []
          const src = tableRows.find((r) => r.id === rowId)
          void store.addRow(tableId, src ? { ...src.cells } : {})
        }
      },
      {
        id: 'table/delete-row',
        section: MenuSection.Context,
        priority: 2,
        label: 'Delete row',
        icon: 'delete',
        danger: true,
        onSelect: () => void useTablesStore.getState().deleteRow(rowId)
      }
    ]
  }
})

// Link / file widgets: their content is a URL or file path, so offer Open and
// Copy. Covers files, images, video, PDFs, the Google document kinds, email,
// and the browser widget's own address.
const LINK_KINDS = ['file', 'image', 'video', 'pdf', 'gdoc', 'gsheet', 'gslide', 'email', 'webview'] as const
for (const kind of LINK_KINDS) {
  registerWidgetContextActions(kind, (ctx) => {
    if (ctx.object.type !== 'widget') return { context: [] }
    const url = (ctx.object.widget.content || '').trim()
    if (!url) return { context: [] }
    const isHttp = /^https?:\/\//i.test(url)
    return {
      context: [
        {
          id: `${kind}/open-external`,
          section: MenuSection.Context,
          priority: 0,
          label: isHttp ? 'Open in browser' : 'Open',
          icon: 'open_in_new',
          onSelect: () => void window.api.files.openExternal(url)
        },
        {
          id: `${kind}/copy-url`,
          section: MenuSection.Context,
          priority: 1,
          label: isHttp ? 'Copy URL' : 'Copy path',
          icon: 'content_copy',
          onSelect: () => {
            void navigator.clipboard.writeText(url).catch(() => {})
          }
        }
      ]
    }
  })
}

// Color swatch: copy the hex value.
registerWidgetContextActions('color', (ctx) => {
  if (ctx.object.type !== 'widget') return { context: [] }
  const hex = (ctx.object.widget.content || '#fbbf24').trim()
  return {
    context: [
      {
        id: 'color/copy',
        section: MenuSection.Context,
        priority: 0,
        label: `Copy ${hex}`,
        icon: 'content_copy',
        onSelect: () => {
          void navigator.clipboard.writeText(hex).catch(() => {})
        }
      }
    ]
  }
})

// Section container: switch the child layout.
registerWidgetContextActions('section', (ctx) => {
  if (ctx.object.type !== 'widget') return { context: [] }
  const w = ctx.object.widget
  const setLayout = (layout: 'free' | 'grid' | 'stacks' | 'list'): void => {
    void useWidgetStore.getState().update(w.id, { layout })
    useWidgetStore.getState().bumpLayoutVersion()
  }
  const opt = (
    value: 'free' | 'grid' | 'stacks' | 'list',
    label: string,
    icon: string,
    priority: number
  ): MenuContribution => ({
    id: `section/layout/${value}`,
    section: MenuSection.Context,
    priority,
    label,
    icon,
    onSelect: () => setLayout(value)
  })
  return {
    context: [
      {
        id: 'section/layout',
        section: MenuSection.Context,
        priority: 0,
        label: 'Section layout',
        icon: 'dashboard_customize',
        children: [
          opt('free', 'Free', 'open_with', 0),
          opt('grid', 'Grid', 'grid_view', 1),
          opt('stacks', 'Stacks', 'view_agenda', 2),
          opt('list', 'List', 'format_list_bulleted', 3)
        ]
      }
    ]
  }
})

// Browser widget: target-aware actions for a right-click inside the embedded
// page (non-editable content). The selection text already flows into AI Assist
// and Create via the menu context; these add the link / image / video actions.
registerWidgetContextActions('webview', 'browser-target', (ctx) => {
  if (ctx.object.type !== 'widget') return { context: [] }
  const w = ctx.object.widget
  const p = ctx.sub?.payload ?? {}
  const linkURL = p.linkURL as string | undefined
  const srcURL = p.srcURL as string | undefined
  const mediaType = p.mediaType as string | undefined
  const rows: MenuContribution[] = []
  if (linkURL) {
    rows.push({
      id: 'webview/open-link',
      section: MenuSection.Context,
      priority: 0,
      label: 'Open link in new browser',
      icon: 'open_in_new',
      onSelect: () => void createConnectedTool({ sourceWidgetId: w.id, kind: 'webview', content: linkURL })
    })
    rows.push({
      id: 'webview/copy-link',
      section: MenuSection.Context,
      priority: 3,
      label: 'Copy link',
      icon: 'link',
      onSelect: () => {
        void navigator.clipboard.writeText(linkURL).catch(() => {})
      }
    })
  }
  if (srcURL && mediaType === 'image') {
    rows.push({
      id: 'webview/save-image',
      section: MenuSection.Context,
      priority: 1,
      label: 'Save image to desk',
      icon: 'image',
      onSelect: () => void createConnectedTool({ sourceWidgetId: w.id, kind: 'image', content: srcURL })
    })
  }
  if (srcURL && mediaType === 'video') {
    rows.push({
      id: 'webview/save-video',
      section: MenuSection.Context,
      priority: 1,
      label: 'Save video to desk',
      icon: 'movie',
      onSelect: () => void createConnectedTool({ sourceWidgetId: w.id, kind: 'video', content: srcURL })
    })
  }
  return { context: rows }
})

export const CORE_PROVIDERS_REGISTERED = true
