// Core widget context-action providers. These contribute the section-1
// (Context band) rows that are specific to a widget. The universal sections
// (AI Assist, Create, Convert, Organise, Share, Advanced, Destructive) are
// added by the resolver for every widget, so a provider only declares what is
// genuinely specific to its kind. Importing this module once registers them.

import { MenuSection } from './types'
import { registerWidgetContextActions } from './registry'
import { useWidgetStore } from '../../stores/widgets'
import { hasChecklist, toggleChecklist } from '../stickyText'

// Sticky: a real widget-specific action that proves the registration path end
// to end. Toggling the checklist is a pure transform on the sticky's text, so
// it is safe to drive from the menu.
registerWidgetContextActions('sticky', (ctx) => {
  if (ctx.object.type !== 'widget') return { context: [] }
  const w = ctx.object.widget
  const checklist = hasChecklist(w.content || '')
  return {
    context: [
      {
        id: 'sticky/checklist',
        section: MenuSection.Context,
        priority: 0,
        label: checklist ? 'Remove checkboxes' : 'Make a checklist',
        icon: 'checklist',
        onSelect: () => void useWidgetStore.getState().update(w.id, { content: toggleChecklist(w.content || '') })
      }
    ]
  }
})

// Living Doc: the document is regenerated by AI, so manual AI Assist rewrites of
// the body would be overwritten on the next cycle. Suppress AI Assist there and
// offer a regenerate-now action in the Context band instead.
registerWidgetContextActions('living-doc', (ctx) => {
  if (ctx.object.type !== 'widget') return { context: [] }
  const w = ctx.object.widget
  return {
    context: [
      {
        id: 'living-doc/regenerate',
        section: MenuSection.Context,
        priority: 0,
        label: 'Regenerate now',
        icon: 'autorenew',
        onSelect: () => void window.api.livingPage.regenerate(w.id)
      }
    ],
    suppress: { 'ai-assist': true }
  }
})

export const CORE_PROVIDERS_REGISTERED = true
